### ISSUE TITLE
plasma-desktop crashed

### ISSUE THREAD

**Issue by zhaoguobin** [jarzebski/Plasma-Wallpaper-DreamDesktop#1] opened 2014-12-27 09:36 UTC
OpenSuse 13.2 x86_64
Qt 4.8.6
KDE 4.14.3
Plasma  4.11.14
1. open wallpaper dialog, select dreamdesktop, add a movie, apply, close the dialog. it works.
2. open wallpaper dialog again, desktop crashed.

```
[swscaler @ 0x7f26c83f8be0] 1104x622 -> 0x0 is invalid scaling dimension
KCrash: Attempting to start /usr/bin/plasma-desktop from kdeinit
```

I think it crashed at [this line](https://github.com/jarzebski/Plasma-Wallpaper-DreamDesktop/blob/master/dreamdesktop.cpp#L259) 

```
SwsContext *img_convert_ctx = sws_getContext(pCodecCtx->width, pCodecCtx->height, pCodecCtx->pix_fmt, dd->boundingWidth, dd->boundingHeight, PIX_FMT_RGB32, useFilter, NULL, NULL, NULL);
```

`dd->boundingWidth` and `dd->boundingHeight` is 0 at the moment.

PS: I like this plugin. Thanks.

**Comment by X4** [comment] 2015-02-01 08:49
I also experienced the same bug as @zhaoguobin.
There is another bug that I'd like to mention. Videos don't scale to the active screen's resolution. I have a dual-monitor setup and the screen on the right has a 1080p resolution, but when I apply a video to it it's only 1280x1024 (the resolution of the left screen).

**Comment by reload2** [comment] 2015-04-03 22:45
Hello, i have the same issue, how can i fix it?

**Comment by voncloft** [comment] 2015-06-07 21:10
Same issue here, I can apply the initial setup on a Gentoo AMD 64 bit system, I open up Desktop Settings, select the video, hit apply and it works, close it out.

Try and change it later down the road and it crashes before I am able to even attempt to change the video.

I am using KDE 4.14.3

**Comment by Fincer** [comment] 2016-04-07 07:04
I have the same issue. What's wrong with the application code?

Initial configuration works flawlessly but once I re-open wallpaper settings, the whole desktop crashes.

Though it may look like that everyone is moving to KDE 5, I still use KDE 4 and hope this crash will be fixed by the developer or anyone who is capable to do so. Otherwise you leave no another choise but to delete this application though it looked very promising at first sight.

I'm disappointed.

**Comment by Fincer** [comment] 2016-04-07 08:55
Right, I narrowed down the issue. The OP was right, the problem is at line (dreamdesktop.cpp)

```
SwsContext *img_convert_ctx = sws_getContext(pCodecCtx->width, pCodecCtx->height, pCodecCtx->pix_fmt, dd->boundingWidth, dd->boundingHeight, PIX_FMT_RGB32, useFilter, NULL, NULL, NULL);
```

And, more specifically, this part of the code:

```
dd->boundingWidth, dd->boundingHeight
```

For some reason, boundingWidth & boundingHeight are set to 0, which causes the crash.

## **Workaround**

I was too lazy to fix this properly, so I did a really dirty patch which fixes the issue for me. Simply replace the line with this:

```
SwsContext *img_convert_ctx = sws_getContext(pCodecCtx->width, pCodecCtx->height, pCodecCtx->pix_fmt, pCodecCtx->width, pCodecCtx->height, PIX_FMT_RGB32, useFilter, NULL, NULL, NULL);
```

A proper fix should get correct Width & Height values for boundingWidth & boundingHeight, which is done between lines _229-240 in dreamdesktop.cpp_.

**This is NOT a proper fix, it's more like a workaround**

Animated video wallpapers don't scale at all, should be fixed, too. Not sure if caused by the workaround method. (this is what X4 already mentioned above)

**Comment by Aruken-V** [comment] 2017-01-18 20:05
The previous work around didn't work for me, as the video would not be resized to match the screen, so I just thought I'd give it a try (although I basically don't know crap about programming LoL). I thought maybe setting the bounding size to the same size of the screen would just work. I tested it on dual, mirror and single monitor and it works as expected. Haven't tried different desktop dispositions but it seems like it should work fine anyways. Ok, so for my work around you have to put this in these lines:

Line 229     dd->boundingWidth = screenWidth;
Line 230     dd->boundingHeight = screenHeight;

This also works with changes on screen size, but it won't update automatically, so you need to go into desktop settings and apply your video wallpaper again.

**Closed as completed** 2023-05-18 10:51 UTC
